/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExportEcosDotcsvRouteImport } from './routes/api/export-ecos[.]csv'
import { Route as ApiExportDecisoesDotcsvRouteImport } from './routes/api/export-decisoes[.]csv'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedPesquisaRouteImport } from './routes/_authenticated/pesquisa'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEcosIndexRouteImport } from './routes/_authenticated/ecos.index'
import { Route as AuthenticatedCausasIndexRouteImport } from './routes/_authenticated/causas.index'
import { Route as AuthenticatedAnalisesIndexRouteImport } from './routes/_authenticated/analises.index'
import { Route as AuthenticatedEcosNovoRouteImport } from './routes/_authenticated/ecos.novo'
import { Route as AuthenticatedEcosIdRouteImport } from './routes/_authenticated/ecos.$id'
import { Route as AuthenticatedCausasNovoRouteImport } from './routes/_authenticated/causas.novo'
import { Route as AuthenticatedCausasIdRouteImport } from './routes/_authenticated/causas.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportEcosDotcsvRoute = ApiExportEcosDotcsvRouteImport.update({
  id: '/api/export-ecos.csv',
  path: '/api/export-ecos.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportDecisoesDotcsvRoute = ApiExportDecisoesDotcsvRouteImport.update({
  id: '/api/export-decisoes.csv',
  path: '/api/export-decisoes.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesquisaRoute = AuthenticatedPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcosIndexRoute = AuthenticatedEcosIndexRouteImport.update({
  id: '/ecos/',
  path: '/ecos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCausasIndexRoute =
  AuthenticatedCausasIndexRouteImport.update({
    id: '/causas/',
    path: '/causas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalisesIndexRoute =
  AuthenticatedAnalisesIndexRouteImport.update({
    id: '/analises/',
    path: '/analises/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcosNovoRoute = AuthenticatedEcosNovoRouteImport.update({
  id: '/ecos/novo',
  path: '/ecos/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcosIdRoute = AuthenticatedEcosIdRouteImport.update({
  id: '/ecos/$id',
  path: '/ecos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCausasNovoRoute = AuthenticatedCausasNovoRouteImport.update({
  id: '/causas/novo',
  path: '/causas/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCausasIdRoute = AuthenticatedCausasIdRouteImport.update({
  id: '/causas/$id',
  path: '/causas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/api/export-decisoes.csv': typeof ApiExportDecisoesDotcsvRoute
  '/api/export-ecos.csv': typeof ApiExportEcosDotcsvRoute
  '/causas/$id': typeof AuthenticatedCausasIdRoute
  '/causas/novo': typeof AuthenticatedCausasNovoRoute
  '/ecos/$id': typeof AuthenticatedEcosIdRoute
  '/ecos/novo': typeof AuthenticatedEcosNovoRoute
  '/analises/': typeof AuthenticatedAnalisesIndexRoute
  '/causas/': typeof AuthenticatedCausasIndexRoute
  '/ecos/': typeof AuthenticatedEcosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pesquisa': typeof AuthenticatedPesquisaRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/api/export-decisoes.csv': typeof ApiExportDecisoesDotcsvRoute
  '/api/export-ecos.csv': typeof ApiExportEcosDotcsvRoute
  '/causas/$id': typeof AuthenticatedCausasIdRoute
  '/causas/novo': typeof AuthenticatedCausasNovoRoute
  '/ecos/$id': typeof AuthenticatedEcosIdRoute
  '/ecos/novo': typeof AuthenticatedEcosNovoRoute
  '/analises': typeof AuthenticatedAnalisesIndexRoute
  '/causas': typeof AuthenticatedCausasIndexRoute
  '/ecos': typeof AuthenticatedEcosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pesquisa': typeof AuthenticatedPesquisaRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/api/export-decisoes.csv': typeof ApiExportDecisoesDotcsvRoute
  '/api/export-ecos.csv': typeof ApiExportEcosDotcsvRoute
  '/_authenticated/causas/$id': typeof AuthenticatedCausasIdRoute
  '/_authenticated/causas/novo': typeof AuthenticatedCausasNovoRoute
  '/_authenticated/ecos/$id': typeof AuthenticatedEcosIdRoute
  '/_authenticated/ecos/novo': typeof AuthenticatedEcosNovoRoute
  '/_authenticated/analises/': typeof AuthenticatedAnalisesIndexRoute
  '/_authenticated/causas/': typeof AuthenticatedCausasIndexRoute
  '/_authenticated/ecos/': typeof AuthenticatedEcosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pesquisa'
    | '/relatorio'
    | '/api/export-decisoes.csv'
    | '/api/export-ecos.csv'
    | '/causas/$id'
    | '/causas/novo'
    | '/ecos/$id'
    | '/ecos/novo'
    | '/analises/'
    | '/causas/'
    | '/ecos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pesquisa'
    | '/relatorio'
    | '/api/export-decisoes.csv'
    | '/api/export-ecos.csv'
    | '/causas/$id'
    | '/causas/novo'
    | '/ecos/$id'
    | '/ecos/novo'
    | '/analises'
    | '/causas'
    | '/ecos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/pesquisa'
    | '/_authenticated/relatorio'
    | '/api/export-decisoes.csv'
    | '/api/export-ecos.csv'
    | '/_authenticated/causas/$id'
    | '/_authenticated/causas/novo'
    | '/_authenticated/ecos/$id'
    | '/_authenticated/ecos/novo'
    | '/_authenticated/analises/'
    | '/_authenticated/causas/'
    | '/_authenticated/ecos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiExportDecisoesDotcsvRoute: typeof ApiExportDecisoesDotcsvRoute
  ApiExportEcosDotcsvRoute: typeof ApiExportEcosDotcsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-ecos.csv': {
      id: '/api/export-ecos.csv'
      path: '/api/export-ecos.csv'
      fullPath: '/api/export-ecos.csv'
      preLoaderRoute: typeof ApiExportEcosDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-decisoes.csv': {
      id: '/api/export-decisoes.csv'
      path: '/api/export-decisoes.csv'
      fullPath: '/api/export-decisoes.csv'
      preLoaderRoute: typeof ApiExportDecisoesDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesquisa': {
      id: '/_authenticated/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof AuthenticatedPesquisaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecos/': {
      id: '/_authenticated/ecos/'
      path: '/ecos'
      fullPath: '/ecos/'
      preLoaderRoute: typeof AuthenticatedEcosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/causas/': {
      id: '/_authenticated/causas/'
      path: '/causas'
      fullPath: '/causas/'
      preLoaderRoute: typeof AuthenticatedCausasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analises/': {
      id: '/_authenticated/analises/'
      path: '/analises'
      fullPath: '/analises/'
      preLoaderRoute: typeof AuthenticatedAnalisesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecos/novo': {
      id: '/_authenticated/ecos/novo'
      path: '/ecos/novo'
      fullPath: '/ecos/novo'
      preLoaderRoute: typeof AuthenticatedEcosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecos/$id': {
      id: '/_authenticated/ecos/$id'
      path: '/ecos/$id'
      fullPath: '/ecos/$id'
      preLoaderRoute: typeof AuthenticatedEcosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/causas/novo': {
      id: '/_authenticated/causas/novo'
      path: '/causas/novo'
      fullPath: '/causas/novo'
      preLoaderRoute: typeof AuthenticatedCausasNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/causas/$id': {
      id: '/_authenticated/causas/$id'
      path: '/causas/$id'
      fullPath: '/causas/$id'
      preLoaderRoute: typeof AuthenticatedCausasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPesquisaRoute: typeof AuthenticatedPesquisaRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedCausasIdRoute: typeof AuthenticatedCausasIdRoute
  AuthenticatedCausasNovoRoute: typeof AuthenticatedCausasNovoRoute
  AuthenticatedEcosIdRoute: typeof AuthenticatedEcosIdRoute
  AuthenticatedEcosNovoRoute: typeof AuthenticatedEcosNovoRoute
  AuthenticatedAnalisesIndexRoute: typeof AuthenticatedAnalisesIndexRoute
  AuthenticatedCausasIndexRoute: typeof AuthenticatedCausasIndexRoute
  AuthenticatedEcosIndexRoute: typeof AuthenticatedEcosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPesquisaRoute: AuthenticatedPesquisaRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedCausasIdRoute: AuthenticatedCausasIdRoute,
  AuthenticatedCausasNovoRoute: AuthenticatedCausasNovoRoute,
  AuthenticatedEcosIdRoute: AuthenticatedEcosIdRoute,
  AuthenticatedEcosNovoRoute: AuthenticatedEcosNovoRoute,
  AuthenticatedAnalisesIndexRoute: AuthenticatedAnalisesIndexRoute,
  AuthenticatedCausasIndexRoute: AuthenticatedCausasIndexRoute,
  AuthenticatedEcosIndexRoute: AuthenticatedEcosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiExportDecisoesDotcsvRoute: ApiExportDecisoesDotcsvRoute,
  ApiExportEcosDotcsvRoute: ApiExportEcosDotcsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
